### ISSUE TITLE
x-axis date formatting. Sundays appear as months

### ISSUE THREAD

**Issue by zzakir** [d3/d3-scale#103]
In d3 js time scale sundays are being displayed as month. For example, in the attached screen shot, instead of Sun 05, it displays Mar 05.
<img width="887" alt="screen shot 2017-05-03 at 10 39 00 am" src="https://cloud.githubusercontent.com/assets/5466170/25648808/6984a1f6-2fed-11e7-8e6b-723785bc46cb.png">

There is also an issue posted in another library which uses d3js as its base.the ljnk is:
https://github.com/FormidableLabs/victory/issues/352

**Comment by mbostock** [comment]
Correct. Please read the API Reference for [*time*.tickFormat](https://github.com/d3/d3-scale/blob/master/README.md#time_tickFormat):

> The default multi-scale time format chooses a human-readable representation based on the specified date as follows:
> 
> * `%Y` - for year boundaries, such as `2011`.
> * `%B` - for month boundaries, such as `February`.
> * `%b %d` - for week boundaries, such as `Feb 06`.
> * `%a %d` - for day boundaries, such as `Mon 07`.
> * `%I %p` - for hour boundaries, such as `01 AM`.
> * `%I:%M` - for minute boundaries, such as `01:23`.
> * `:%S` - for second boundaries, such as `:45`.
> * `.%L` - milliseconds for all other times, such as `.012`.
> 
> Although somewhat unusual, this default behavior has the benefit of providing both local and global context: for example, formatting a sequence of ticks as [11 PM, Mon 07, 01 AM] reveals information about hours, dates, and day simultaneously, rather than just the hours [11 PM, 12 AM, 01 AM]. See [d3-time-format](https://github.com/d3/d3-time-format) if you’d like to roll your own conditional time format.

**Comment by yashshree-cg** [comment]
Please go through [multi scale time format](https://github.com/d3/d3-3.x-api-reference/blob/master/Time-Formatting.md#format_multi) 
where we have following code:
`var format = d3.time.format.multi([
  [".%L", function(d) { return d.getMilliseconds(); }],
  [":%S", function(d) { return d.getSeconds(); }],
  ["%I:%M", function(d) { return d.getMinutes(); }],
  ["%I %p", function(d) { return d.getHours(); }],
  ["%a %d", function(d) { return d.getDay() && d.getDate() != 1; }],
  ["%b %d", function(d) { return d.getDate() != 1; }],
  ["%B", function(d) { return d.getMonth(); }],
  ["%Y", function() { return true; }]
]);`

Here when value is _[Sunday 05](url)_, this below condition  **["%a %d", function(d) { return d.getDay() && d.getDate() != 1; }]** should return true but it returns false because first part of && condition(i.e. d.getDay()) returns 0 for sunday and 0 && anything will be false...
so just change this to 
**["%a %d", function(d) { return d.getUTCDay() <= 6 && d.getUTCDate() !== 1; }]**

**Comment by mbostock** [comment]
@yashshree-cg Please see the 4.x code here:

https://github.com/d3/d3-scale/blob/4c8c282d5f0ac938b4841ce6851389e7f0f545ba/src/time.js#L60-L68
