### ISSUE TITLE
Linear scale with one value generates no tick.

### ISSUE THREAD

**Issue by kanitw** [d3/d3-scale#113]
```
d3.scaleLinear().domain([4,4]).range([0,100]).ticks()
``` 

produces

```
[]
```

as a result, an axis from this scale would have no tick, which would be quite confusing for users

![image](https://user-images.githubusercontent.com/111269/29202103-94dd6ef8-7e19-11e7-81c7-f3027c161e7e.png)

It might be better to generate a single tick and place items at the midpoint of the range rather than the minimum point just like what Tableau does:

![image](https://user-images.githubusercontent.com/111269/29202121-bf21d6d6-7e19-11e7-9fb5-133e021c59ed.png)

**Comment by mbostock** [comment]
Fixed in [d3-array@1.2.1](https://github.com/d3/d3-array/releases/tag/v1.2.1). Thanks for the report!

**Comment by kanitw** [comment]
cc: @jheer

**Comment by jheer** [comment]
The fix in d3-array 1.2.1 does indeed add tick marks for singular domains. Thanks!

The report above also included a request for having singular domain values map to the middle of the scale range rather than the start of the range. Is there interest in supporting this aspect as well, or should we assume that the D3 scale convention will not change? Thanks again.

**Comment by mbostock** [comment]
Can you file a separate issue? I think that’s doable but it is a bigger change.

**Comment by mbostock** [comment]
Filed as #117.

**Comment by mbostock** [comment]
This will be fixed in #156 d3-scale 2.2.
