### ISSUE TITLE
Edge 'slice'

### ISSUE THREAD

**Issue by tobi12345** [d3/d3-scale#115]
TypeError: Object doesn't support property or method 'slice'

some times typeof domain is 'function' only appears in edge(IE is working :D )

*/node_modules/d3-scale/src/continuous.js:94 (called from scale.ticks)
```
  92 | scale.domain = function (_) {
  93 |   console.log(typeof domain, domain)
> 94 |   return arguments.length ? (domain = map.call(_, number), rescale()) : domain.slice();
  95 | };
```

**Comment by mbostock** [comment]
Sorry, but unfortunately this isn’t enough information for me to reproduce and investigate this issue. The value of `domain` here should always be an array, as it was constructed by calling *array*.map, and therefore should always support *array*.slice. I can’t see any code path where `domain` becomes a function.

When reporting an issue, please include a link to a live example, preferably on [bl.ocks.org](http://bl.ocks.org) or [RunKit](https://runkit.com/npm/d3-scale), or as a pull request in the [appropriate repository](https://github.com/d3) with new unit tests, that demonstrates that the described behavior is not the [expected behavior](https://github.com/d3/d3/blob/master/API.md). Use only the minimum amount of code necessary to reproduce the unexpected behavior.

Non-actionable bugs may be temporarily closed until you provide additional information. If you can’t isolate the bug any further, please let me know and I will try to help. However, I beg your patience: I must balance your request against many other responsibilities—fixing other bugs, answering other questions, new features, new documentation, *etc.* Please also consider asking for help on [Stack Overflow](https://stackoverflow.com/tags/d3.js).

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by alexanderby** [comment]
This is [MS Edge issue](https://github.com/Microsoft/ChakraCore/issues/1415) and should be fixed in latest version. For some reason this happens when D3 is bundled using Webpack.
[Here](https://github.com/Tragetaschen/ms-edge-d3-scale-issue-1415) is the repository showing bug and [here](https://jsfiddle.net/kmb4tpqd/2/) you can see it online, if you open the page without opening DevTools.

And [here](https://github.com/Microsoft/ChakraCore/issues/1415#issuecomment-287888807) is a workaround.
