### ISSUE TITLE
Scale Band produces incorrect range starting point with rounding

### ISSUE THREAD

**Issue by Barrot** [d3/d3-scale#116]
It seems that the scaleBand produces a wrong starting points for scales with domains of > 10 items and rounding turned on.

Example:
```javascript
var scale = d3.scaleBand().domain(d3.range(92)).rangeRound([25,1475])
scale(0) // produces 60, when 25 is expected
```

while:

```javascript
var scale = d3.scaleBand().domain(d3.range(10)).rangeRound([25,1475])
scale(0) // produces 25
```
It seems that the disconnect starts gradually happening with domain of more than 10 items. I've attempted using multiple range values with the same effect observed.

**Comment by mbostock** [comment]
This is the expected behavior. The issue is that rounding requires rounding down so that all of the bands fit in the available range. If you have many bands, there is leftover space as a result of rounding down. By default this extra space is distributed equally on either side of the bands; you can change how this space is distributed using [*band*.align](https://github.com/d3/d3-scale/blob/master/README.md#band_align).

To illustrate, the top-oriented axis is without rounding, and the bottom-oriented axis is with rounding:

<img width="1494" alt="screen shot 2017-09-23 at 1 19 36 pm" src="https://user-images.githubusercontent.com/230541/30776811-2dd3b134-a062-11e7-823a-74a2273a0291.png">

The [bandwidth](https://github.com/d3/d3-scale/blob/master/README.md#band_bandwidth) prior to rounding is approximately 15.76px. This is rounded down to 15px. That leaves 0.76px * 92 = ~70px of extra space due to rounding, which is then distributed evenly on either side of the bands with the default align of 0.5. Hence scale(0) returning 25 + 70 / 2 = 60.

This is less apparent when there are fewer bands because the extra space introduced by rounding is diminished.

<img width="1488" alt="screen shot 2017-09-23 at 1 26 42 pm" src="https://user-images.githubusercontent.com/230541/30776845-dd75a82c-a062-11e7-8313-5164a0cff7b0.png">

**Comment by Barrot** [comment]
Thanks for the explanation. Using _band_.align with value 0 fixed the issue.
