### ISSUE TITLE
Rollup and color methods from scale are unnecessarily being included

### ISSUE THREAD

**Issue by nonmetalhail** [d3/d3-scale#127]
Hi,

I'm using Rollup to create a d3 bundle. I'm only importing the following modules:
```
export {
  scaleUtc,
  scaleTime,
  scaleLinear,
  scaleBand,
  scalePoint
} from "d3-scale";
export * from "d3-quadtree";
```

What I'm seeing is that the color related methods from d3-scale are included in my bundle: all the category files, cubehelix, rainbow, and viridis, and then of course, their dependencies. These still get included even when I reduce my scale imports to just one of the above modules. Deleting the export statements from index.js does prevent them from being imported, which serves to confirm that they are coming from d3-scale and not elsewhere. This is bugging me because, without these, I could eliminate d3-color from my bundle and save a fair amount of space. 

What I'm wondering is if it is possible to stop these unnecessary color methods from being imported? I've not been able to track down exactly where they are being imported from and whether this is intentional that they always get included or a bug. If they are being brought in via some circular dependency, perhaps it is possible to change the imports and resolve this?

**Comment by mbostock** [comment]
Sorry, but this is a Rollup issue, not a D3 issue. Rollup has made a lot of improvements recently to its tree-shaking algorithm, but it seems like it’s still not smart enough to tree-shake all the dead code here.

You can help Rollup (at the cost of making your code slightly more brittle to version upgrades) by importing the file that defaults scaleLinear (and the other scales) directly rather than using the default entry. For example, this produces a 76KB bundle:

```js
export {
  scaleLinear
} from "d3-scale";
```

But this produces a 40KB bundle:

```js
export {
  default as scaleLinear
} from "d3-scale/src/linear";
```

It’s possible to rewrite the D3 code to make it easier for Rollup to determine that it has no side-effects, and therefore tree-shake more effectively, but I’m not going to rewrite the code solely for the benefit of Rollup’s tree-shaking algorithm. (If an unrelated improvement has the side-effect of making it easier for Rollup, that’d be welcome, however.) 

I expect Rollup will continue to get better but you’ll probably need to use workarounds like the above if you want smaller bundles.

**Comment by nonmetalhail** [comment]
Sweet, that certainly does what I need for now. Thanks!
