### ISSUE TITLE
scale.nice() returns values outside domain for values less than 1

### ISSUE THREAD

**Issue by ekh64** [d3/d3-scale#133]
In playing around with percentages in scales, I discovered if I have `domainValues < 1`, `scale.nice()` produces a domain with a max value outside of the original domain. Whereas for `domainValues >=1`, the `scale.nice()` would be restricted to the original domain.

Example 1:
`scale.domain([0,0.28]).nice()` => `[0,.3]`

Example 2:
`scale.domain([0, 28]).nice()` => `[0, 28]`

The behavior for the first example was actually what I needed for my visualization, and I think it could be done for example 2 (returning `[0,30]`) to create nicer niced scales.

**Comment by mbostock** [comment]
This is because 0.28 does not exactly equal 28 / 100 in IEEE 754 binary floating point. It’s slightly bigger.

```
(0.28).toFixed(32) // "0.28000000000000002664535259100376"
```

So a more precise comparison would be:

```js
d3.scaleLinear().domain([0, 28.000000000000002664535259100376]).nice().domain()
```

Which returns a domain of [0, 30], similar to how the smaller domain returns [0, 0.3].

Nicing strictly increases the size of the domain, so if the upper bound of the domain is greater than the exact value of 0.28 (which 0.28 in IEEE 754 is), then any nicing will result in a bigger domain. Unfortunately, there’s not really a way for our API to distinguish between you setting the upper bound of the domain to 0.28 exactly and setting it to 0.28000000000000003.
