### ISSUE TITLE
Scale gives different results in the v5.8

### ISSUE THREAD

**Issue by Atralbus** [d3/d3-scale#161]
The code below is giving `2014 0` as an output in the `v5.5`.
```
const scale = d3.scaleLog().clamp(true)
 .rangeRound([150, 0])
 .domain([2009, 2014])
console.log(scale.invert(0), scale(2014))
```
But after switching to the v5.8, I realized that now it's giving `2013.999999999999 0`. Is there a way to fix it without explicitly rounding the numbers?

**Comment by mbostock** [comment]
Due to floating point precision, we don’t guarantee that *scale* or *scale*.invert return exact values in the range or domain, respectively. The implementation changed in 5.8 to allow for generic transformations on continuous scales.

Why do you require exact values in your application? What I’d recommend depends on what you are trying to do.

**Comment by Atralbus** [comment]
@mbostock Thanks for the clarification. I have a logarithmic line chart where I'm selecting a range on the y axis with a brush. Inside the `end` event of brush, `scale.invert` returns `2013.999999999999` and prevents me to select the value `2014` at the top. And I don't want to round numbers coming from `scale.invert` in there because I also want to be able select continuous values.
