### ISSUE TITLE
scale.accessor?

### ISSUE THREAD

**Issue by Fil** [d3/d3-scale#181]
I've been entertaining this idea that a scale would know how to access the value it needs from the data; i.e. instead of applying color(d.species), we would define color.accessor(d => d.species) and use color(d).

~~~
color = d3.scaleOrdinal(["orange", "lime", "yellow"]).accessor(d => d.species)
data = [{ species: 1 }, { species: 2 }, { species: 3 }, { species: 1 }]

data.map(color) // ["orange", "lime", "yellow", "orange"] 
~~~

*scale*.accessor is readable:
~~~
data.map(color.accessor()) // [1, 2, 3, 1]
~~~

(If we want this, it would have to be generalized to all scale types.)

See https://observablehq.com/d/01ec707583c3648c

**Comment by mbostock** [comment]
Protovis had this:

https://mbostock.github.io/protovis/jsdoc/symbols/pv.Scale.html#by

**Comment by Fil** [comment]
Is this something that you think could be included if I did a PR?

**Comment by mbostock** [comment]
Not at the moment, sorry.

There’s a ton of stuff on the list for D3 6.0, and I’m trying to focus on getting that released. There are some feature requests still to implement, but most of them have been baking for a while so I’m confident they are good additions.

For a scale accessor, my past experience with Protovis tells me that it can be awkward because often you want to use a scale both with a datum of a given structure and with raw values directly. And for scales more generally, I want to consider making them immutable, and see if we can move away from function subclasses and adopt conventional ES classes.

**Comment by mbostock** [comment]
Punting on this for now unless I can be convinced otherwise. :smile:
