### ISSUE TITLE
scaleLinear not exported by d3-scale.v3.js?

### ISSUE THREAD

**Issue by mikemaccana** [d3/d3-scale#185]
**Really sorry to bother you with this**, I've been using CommonJS for years but am less familiar with ES2015 module syntax. I and am attempting to replicate this [Svelte example using D3 scale](https://svelte.dev/examples#area-chart) 

Using https://d3js.org/d3-scale.v3.js

    import { scaleLinear } from '../thirdparty/d3-scale.v3.js'

Results in:

    [!] Error: 'scaleLinear' is not exported by src\frontend\thirdparty\d3-scale.v3.js

How can I import `scaleLinear`? I have attempted to understand how d3-scale is doing it's exports but there is some magic using `defineProperty()` that I don't understand the rationale behind.

**Comment by mbostock** [comment]
The d3-scale.v3.js you’re referring to is not an [ES module](https://exploringjs.com/es6/ch_modules.html); it’s a [UMD](https://github.com/umdjs/umd) that’s intended to be used from CommonJS, AMD (e.g., [d3-require](https://github.com/d3/d3-require)) or as a script element with global export.

If you want the ES module entry point, it’s the [`module` field](https://github.com/d3/d3-scale/blob/b5410a4f04411df8f5c6a7a600acc8441fb963cd/package.json#L20) in the package.json, which is currently [src/index.js](https://github.com/d3/d3-scale/blob/master/src/index.js). However, because d3-scale has external dependencies (such as d3-interpolate), it uses [bare imports](http://dplatz.de/blog/2019/es6-bare-imports.html). You’ll either need a bundler that knows how to resolve these dependencies (such as Rollup) or an [import map](https://github.com/WICG/import-maps).

(See also https://github.com/d3/d3/issues/3336.)
