### ISSUE TITLE
Direct Linking

### ISSUE THREAD

**Issue by SciutoAlex** [d3/d3-scale#2]
Is this a stupid question, I'm not sure. 

But is the thinking that these modules will be available to directly include in an html document like `<script src="./js/d3-scales.js"></script>`? Or will you need to do some kind of npm + browserify workflow?

I'm trying to think about this for beginners or people not familiar with package managers and specifically Node. Is the idea that these kinds of people will just stick with the full d3 suite, and that the modules are intended for more advanced people?

@arnicas, I thought I'd ask this question over here instead of in this processing/p5.js#730 discussion.

**Comment by mbostock** [comment]
I’m trying to support as many use cases as I can. (Which is difficult, because JavaScript tooling is so fragmented.) So…

Yes, you can use vanilla script tags to load scale.js in a browser, in which case it will define a `scale` global. You can also use a loader that understands AMD to load it asynchronously without a global, such as RequireJS. You can also integrate the provided scale.js with Browserify, webpack, or any other build tool which understands UMD or ES6 modules.

Yes, you can download the latest release using NPM as `npm install d3-scale`, but you can also download the [latest release](https://github.com/d3/d3-scale/releases/tag/v0.0.2) directly in your browser.

If you want to use only *part* of the d3-scale module (like say you only use linear scales, and don’t want to include ordinal scales), then you can use [d3-bundler](https://github.com/d3/d3-bundler) to create a custom build. See [bl.ocks.org/bb09af4c39c79cffcde4](http://bl.ocks.org/mbostock/bb09af4c39c79cffcde4) for an example. In the future, there will be a point-and-click web interface for creating a custom build. But for now you should either use the pre-built release, or run d3-bundler yourself.

**Comment by mbostock** [comment]
There are some cases where you can get duplicate code if you include multiple D3 modules that share dependencies. For example, if you load [d3-interpolate](https://github.com/d3/d3-interpolate) and [d3-scale](https://github.com/d3/d3-scale), you’ll get some duplicate code because d3-scale already uses parts of d3-interpolate, and both d3-scale and d3-interpolate depend on d3-color. The recommended way to avoid this duplication is to create a custom build using d3-bundler. You should also be able to use an ES6 module loader, such as [SystemJS](https://github.com/systemjs/systemjs), but I haven’t tried that myself.

**Comment by SciutoAlex** [comment]
Thanks, Mike! 

I think it'd be helpful to include scale.js and scale.min.js in the root directory in github. I know that's where I look first when I want to quickly grab a library and include it.

**Comment by mbostock** [comment]
I don’t include generated files in the git repository. It’s a hassle for development and a bad practice that people should move away from.
