### ISSUE TITLE
`Invalid Date`s cause `scaleTime.ticks` to loop forever

### ISSUE THREAD

**Issue by seansfkelley** [d3/d3-scale#65]
Here's a snippet that will lock up whatever you run it in:

```
d3Scale.scaleTime().range([0, 100]).domain([-1e50, 1e50]).ticks(5)
```

The root cause appears to be a [`while` loop in d3-time](https://github.com/d3/d3-time/blob/edfff22c6015425eccd2aad7dcc1740f83989113/src/interval.js#L37) which is called in [d3-scale by `interval.every`](https://github.com/d3/d3-scale/blob/3cc1011277bb2a1df81d1e4e7a9774f113d386f3/src/time.js#L87). I'm not sure what an appropriate response by d3 would be here (throw? propagate `Invalid Date`?). I'm filing this issue here because I'm not sure in which module it would be appropriate to handle this edge case.

**Comment by mbostock** [comment]
In general, if you ask D3 to do something expensive, there’s often not a good way to detect the expensive nature of the request ahead of time and handle it specially such as by throwing an error. It’s just like if you wrote a for loop, `for (var i = -1e50; i < 1e50; ++i);`: that’s going to take a while and JavaScript doesn’t do anything special to protect you. Though D3 *does* detect some requests that are obviously uncomputable. For example, d3.range(Infinity) returns the empty array.

In this specific case, we can improve the performance by using a non-filtering time interval, so that the cost of skipping many years is O(1) rather than O(*n*). It would be hard to do this for all time intervals, since time intervals are complicated. But it should be easy to do this for years, and then change d3.scaleTime (and d3.scaleUtc) to use a multi-year interval rather than filtering the year interval.

However, I’d guess you’d also want to constrain zooming on your chart so that the domain doesn’t end up as [-1e50, 1e50]. I doubt that JavaScript’s Date makes much sense at that scale.

**Comment by mbostock** [comment]
It appears the proposed optimization is actually not necessary in this case because the domain is invalid:

```js
new Date(-1e50); // Invalid Date
new Date(1e50); // Invalid Date
```

This is equivalent to NaN, so that should be obviously uncomputable in the same fashion as this:

```js
d3.scaleLinear().domain([NaN, NaN]).ticks(5); // []
```

**Comment by seansfkelley** [comment]
Agreed that d3 can't be expected to detect every expensive operation, but I thought I should file this anyway since the failure mode is really pernicious/hard to debug (infinite loop deep in a library) and the detection of the condition seems fairly straightforward (`Invalid Date`s are pretty self-descriptive). 

And yeah, `1e50` is just a lazy way to get an `Invalid Date`. While writing this comment I attempted to come up with another repro demonstrating a non-numerical issue yielding an `Invalid Date`, but evidently the error handling is not where I thought it was, because this returns `[]` immediately:

```
d3Scale.scaleTime().range([0, 100]).domain([new Date('fsdfsdg'), new Date('dsfjhsdkg')]).ticks(5)
```

**Comment by mbostock** [comment]
Yes, the time scale already handles the case where the domain is invalid. In that case, the computed tick interval is null (because calling [*interval*.every](https://github.com/d3/d3-time#interval_every) with NaN returns null), and so you get the empty ticks.

But your code is exploiting a weakness of d3.scaleTime because it relies on coercion. Note that it says this:

```js
d3.scaleTime().domain([-1e50, 1e50])
```

And not this:

```js
d3.scaleTime().domain([new Date(-1e50), new Date(1e50)])
```

Internally the time scale is backed by a linear scale. The problem is that the time scale isn’t greedily coercing to Date before setting the linear scale’s numeric domain, so the resulting domain internally is [-1e50, 1e50] rather than [NaN, NaN].

**Comment by mbostock** [comment]
I’ve fixed d3-scale to coerce the time scale’s domain to dates, so now the domain is invalid in both cases, and the ticks are empty. I also optimized d3.timeYear.every(*k*) and d3.utcYear.every(*k*), so these are now fast for large *k*. Thanks for the report.

**Comment by seansfkelley** [comment]
Love it, thank you for the quick fix and release!
