### ISSUE TITLE
sequential.interpolate?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-scale#67]
Should you be able to access or change a sequential scale’s interpolator after construction?

**Comment by curran** [comment]
IMO it would be nice to be able to access and change the interpolator.

Imagine a visualization that allows interactively changing the interpolator. One example of something similar is the interaction in http://colorbrewer2.org/ that lets you try out different color schemes on a map.

![image](https://cloud.githubusercontent.com/assets/68416/16178011/2160622a-365b-11e6-9f97-b0aea7d3e83d.png)

![image](https://cloud.githubusercontent.com/assets/68416/16178017/38d4865c-365b-11e6-936d-224cde891756.png)

Creating an interface like this for sequential scales with the current API would require recreating the entire scale each time a new interpolator is selected. This means in order to change the interpolator, one needs to also set the domain and range again on the new instance.

**Comment by curran** [comment]
Here's an example of an interface like this with sequential scales: http://bl.ocks.org/curran/3094b37e63b918bab0a06787e161607b

![image](https://cloud.githubusercontent.com/assets/68416/16178276/13dc1f94-3661-11e6-934d-588fd7f4fd08.png)

Code that updates the interpolator:

```js
function setSelectedInterpolator(name){
  var interpolatorName = "interpolate" + name;
  console.log(interpolatorName);

  // To change the interpolator, one must re-create the scale,
  z = d3.scaleSequential(d3[interpolatorName])

    // and set the domain again.
    .domain([0, d3.max(buckets, function(d) { return d.count; })]);

  svg.selectAll(".tile")
    .style("fill", function(d) { return z(d.count); });
}
```

**Comment by mbostock** [comment]
Send me a pull request? Should be an easy one. 😄

**Comment by curran** [comment]
Sure, I'll take a stab at it!
