### ISSUE TITLE
d3 weighted scale - different bandwidth by domain value

### ISSUE THREAD

**Issue by asafbe** [d3/d3-scale#77]
I'm looking for the best option in d3 (V4) to create some kind of weighted scale, so the bandwidth of each band will be calculated based on his domain value. If my domain contains the weight of each band, I would like to get the scale respectively.

For example -

Domain = [1,4,5]
Range = [0,100]

the bandwidth for item#1 will be 10, the bandwidth of item#2 will be 40, etc.

Thanks

**Comment by mbostock** [comment]
I’m not sure how you would distinguish values with the same weight in that design, given that in most scales the domain values uniquely identify the input to the scale. For example, if your domain is [1,4,1], then the bandwidth for the first and last 1 could be the same (16.667), but the positions should presumably be different.

You can probably use a linear scale for this, with a little extra math, as shown here:

https://bl.ocks.org/mbostock/1624660

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/). Thank you! 🤗

**Comment by asafbe** [comment]
@mbostock , you totally right, but in my case I would like to use the index of the domain to get the positions.

**Comment by mbostock** [comment]
My point is you’d probably need something parallel to the domain to specify the weights if that’s the API you wanted to use, like,

domain = ["foo", "bar", "baz"]
weight = [1, 4, 5]
range = [0, 100]

Then you could say *scale*("foo") and it would return the position of the foo band, and it would know that the weight of foo should be 1. Whereas *scale*("bar") would have a weight of 4 and so on. You’d need to make sure that the cardinality of the weights is the same as the domain, of course. Alternatively you could have a weight accessor function or some such that returns the weight for the corresponding domain value, but I think parallel arrays are probably the better way to do it, given how scales already work.

Alternatively maybe scales aren’t the right place for this logic and it’d be better to think about this as a [stacked layout](https://github.com/d3/d3-shape/blob/master/README.md#stacks) instead. Then you can stack your values [1, 4, 5], converting them to intervals, and then use a linear scale or similar to map them to a range.

I’m going to close this issue because I have no plans on implementing a weighted scale in the near future and I think you’ve got some options to work with, but feel free to keep me informed of your progress if you discover a better way to implement this.
