### ISSUE TITLE
scaleTime.ticks(interval) causes 100% CPU in Chrome 53

### ISSUE THREAD

**Issue by clayzermk1** [d3/d3-scale#78]
## What happens?
If I call `.ticks(interval)` on a `scaleTime`, Chrome 53 hits 100% CPU and does not recover.
[Minimum reproducible case - warning will probably crash the tab](https://jsfiddle.net/clayzermk1/3jdvynap/)

## What did you expect to happen?
I expected `.ticks(interval)` to do its magic and adjust the scale's ticks.

## Environment
OS X 10.11.6 (15G31)
Chrome 53.0.2785.116 (64-bit)
d3 4.2.5

## Comments
Am I doing something horribly wrong here? If I comment out the ticks call it works fine. I took the ticks call straight from the [API docs](https://github.com/d3/d3-scale#time_ticks) example for an interval argument. Please let me know if I can provide any additional information. Thank you for your time and for d3!

**Comment by mbostock** [comment]
Your data is strings, not JavaScript Date instances. You need to parse the strings and convert them to Dates before calling d3.extent and before setting the domain. I recommend using d3-time-format for parsing. (You can also use the Date constructor, but its behavior varies from browser to browser.) A d3.scaleTime will coerce numbers representing milliseconds since epoch to dates, but it does not parse strings.

There is a bug here in that the scale should generate zero ticks with an invalid domain rather than going into an infinite loop. There should be checks in place; I will investigate further when I am back at a computer.

**Comment by mbostock** [comment]
Here’s a reduced test case:

```js
var x = d3.scaleTime().domain([NaN, NaN]);
x.ticks(d3.timeMinute.every(15)); // Infinite loop!
```

Or even shorter:

```js
d3.timeMinute.every(15).range(NaN, NaN); // Infinite loop!
```

So, this is a problem with the implementation of [*interval*.every](https://github.com/d3/d3-time/blob/master/src/interval.js#L50): the resulting filtered interval’s test function always returns false because the date is invalid.

**Comment by clayzermk1** [comment]
Thanks @mbostock for such a quick response.

> Your data is strings, not JavaScript Date instances.

Whoops, in my actual code they are Moment instances, but same problem - thank you!

I found that I actually wanted `axis.ticks()`, but knowing where the issue lies helped a ton. I threw guards around my data that I was feeding into `extent`.

Thank you again!

**Comment by mbostock** [comment]
Hmm. Moment instances should actually be fine, because moments coerce the same way as dates:

```js
+moment("2016-03-12 10:00:00"); // 1457805600000
new Date(1457805600000); // Sat Mar 12 2016 10:00:00 GMT-0800 (PST)
```

Thus, it’s valid to use d3-array methods with moment instances, because the [relational operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comparison_Operators#Relational_operators) (such as `<`) use *object*.valueOf to coerce the moments to numbers before comparing:

```js
moment("2016-03-12 10:00:00") < moment("2016-03-12 11:00:00"); // true
```

For example, d3.min:

```js
var moments = [
  moment("2016-03-12 10:00:00"),
  moment("2016-03-12 12:00:00"),
  moment("2016-03-12 11:00:00"),
  moment("2016-03-12 09:00:00")
];

d3.min(moments) === moments[3]; // true
```

If you set a time scale’s domain using moments, they are likewise coerced to numbers and then converted to date instances:

```js
var x = d3.scaleTime().domain([
  moment("2016-03-12 10:00:00"),
  moment("2016-03-12 12:00:00")
]);

x.domain()[0]; // Sat Mar 12 2016 10:00:00 GMT-0800 (PST)
x.domain()[1]; // Sat Mar 12 2016 12:00:00 GMT-0800 (PST)
```

Thus, you can use moments for the domain, and subsequently generate ticks (which will be Date instances, not moments):

```
x.ticks(d3.timeMinute.every(15));
```

https://runkit.com/57d8702e1ff21014007f12d5/57e402c37fd484130015dba8

So, I still suspect your moments were being converted to strings before being passed to d3.extent or *scale*.domain, but hopefully the above explanation is helpful.

**Comment by clayzermk1** [comment]
I think I was hitting the bug on the first pass, where I was passing in an empty data set. `extent` was returning `[undefined, undefined]` (totally sensible for an empty data set) which was being set as the domain of the scale. Calling `ticks` subsequently would then hit the 100% CPU issue.

By adding the guards, I guarantee my data set always has a single (bogus) data point. Totally a hack to work around the `ticks`/`every` issue, but it works for now.

> Moment instances should actually be fine, because moments coerce the same way as dates

Yeah, moments seemed to work just fine before I tried to modify the ticks.

Thank you again!

**Comment by mbostock** [comment]
Ah, okay. Glad we got to the bottom of this. That makes sense! I’m pushing a new release with this fix now,.

**Comment by clayzermk1** [comment]
Killer, thank you!
