### ISSUE TITLE
Map string to color 

### ISSUE THREAD

**Issue by nvdv** [d3/d3-scale#85]
Recently I needed to map a few strings to a color range and come up with this solution

```javascript 
const HASH_LENGTH = Math.pow(2, 20) - 1;

function getHash(str) {
  return crc32(str) & HASH_LENGTH;
}

let data = [
  "Some blues are sad",
  "But some are glad",
  "Dark-sad or bright-gald",
  "They're all blues",
  "All shades, all hues, all blues"
];

let color = d3.scale.linear()
  .domain([0, HASH_LENGTH])
  .range(['#ffffcc', '#006837']);

d3.select('body')
  .selectAll('.textbar')
  .data(data)
  .enter()
  .append('div')
  .attr('class', 'textbar')
  .style('background', d => color(getHash(d)))
  .text(d => d);
```
Function `crc32(str)` just returns integer hash of string `str`.  

This problem arises from time to time and it might be useful to have this solution (maybe in different form) as a part of `d3`.
I wasn't sure if this is correct repo for this request, so feel free to move it if needed.

Thanks!

**Comment by mbostock** [comment]
Is your data categorical or ordinal?

If it’s categorical, I would suggest using a categorical color scheme, rather than your current scheme which has an obvious order (light-to-dark). Using an ordinal color scheme with categorical data implies an order to the data which could be misleading. Here are some recommended categorical color schemes:

* [d3-scale’s category schemes](https://github.com/d3/d3-scale/blob/master/README.md#category-scales)
* [d3-scale-chromatic’s category schemes](https://github.com/d3/d3-scale-chromatic/blob/master/README.md#categorical)

There’s also [Colorgorical](http://gramaz.io/colorgorical/) if you want to design a new categorical color scheme.

Regardless of whether your data is categorical or ordinal, you should be using [d3.scaleOrdinal](https://github.com/d3/d3-scale/blob/master/README.md#ordinal-scales) to implement them mapping from a discrete set of strings to a discrete set of colors, rather than hashing the strings. The name “ordinal scale” here is arguably misleading since it can *also* be used for categorical scales; the “order” is the order in which you specify the domain. For example:

```js
var color = d3.scaleOrdinal()
    .domain(data)
    .range(d3.schemeCategory10);
```

You can also not specify a domain explicitly and let it be [assigned implicitly](https://github.com/d3/d3-scale/blob/master/README.md#ordinal_domain):

```js
var color = d3.scaleOrdinal()
    .range(d3.schemeCategory10);
```

Or, equivalently:

```js
var color = d3.scaleOrdinal(d3.schemeCategory10);
```

If your data is ordinal, I recommend using ColorBrewer’s sequential schemes (or diverging schemes, depending on the application), which are available in [d3-scale-chromatic](https://github.com/d3/d3-scale-chromatic):

* [Sequential (Single Hue)](https://github.com/d3/d3-scale-chromatic/blob/master/README.md#sequential-single-hue)
* [Sequential (Multi-Hue)](https://github.com/d3/d3-scale-chromatic/blob/master/README.md#sequential-single-hue)
* [Diverging](https://github.com/d3/d3-scale-chromatic/blob/master/README.md#diverging)

With an ordinal scale, you typically want to specify the domain explicitly, so that the order is correctly applied in the visual encoding. For example, assuming `data.length` is between 3 and 9:

```js
var color = d3.scaleOrdinal()
    .domain(data)
    .range(d3.schemeBlues[data.length]);
```

The d3-scale-chromatic schemes are available in both continuous (*e.g.*, d3.interpolateBlues) and discrete forms (*e.g.*., d3.schemeBlues). You can use [d3.quantize](https://github.com/d3/d3-interpolate/blob/master/README.md#quantize) to convert a continuous color scheme into a discrete color scheme, but generally speaking the discrete ones built-in to d3-scale-chromatic are better, and you probably don’t want more than nine sequential colors anyway (or 11 for diverging).

```js
var color = d3.scaleOrdinal()
    .domain(data)
    .range(d3.quantize(d3.interpolateBlues, data.length));
```

If you insist on designing your own ordinal color scheme despite the fantastic existing ones available in ColorBrewer, the recommended way to do that is to compute an array of colors using an [interpolator](https://github.com/d3/d3-interpolate), and then set that as the [range](https://github.com/d3/d3-scale/blob/master/README.md#ordinal_range) of your ordinal scale. For example, here’s how you’d implement your current ordinal color scheme using [d3.interpolateRgb](https://github.com/d3/d3-interpolate/blob/master/README.md#interpolateRgb) and:

```js
var data = [
  "Some blues are sad",
  "But some are glad",
  "Dark-sad or bright-gald",
  "They're all blues",
  "All shades, all hues, all blues"
];

var color = d3.scaleOrdinal()
    .domain(data)
    .range(d3.quantize(d3.interpolateRgb("#ffffcc", "#006837"), data.length));

color("Some blues are sad");
```

Of course, it’d be better to use [gamma-corrected RGB interpolate](https://github.com/d3/d3-interpolate/blob/master/README.md#interpolate_gamma) or a perceptual color space such as d3.interpolateHcl or d3.interpolateLab. See also [d3-cam02](https://github.com/connorgr/d3-cam02) and Gregor Aisch’s [Chroma.js Color Scale Helper](http://vis4.net/labs/multihue/).

**Comment by nvdv** [comment]
Thanks for very detailed answer!
It seems that I oversimplified the solution to my problem in description of this issue, but now I clearly see that it should not be part of d3.
Number of strings I needed to map to color range is quite large (so large that I am doing this on backend). Also I want mapping to be reproducible (e.g. "foo" will be mapped to "red" every time mapping is performed) and as fast as possible (constant time is preferable). 
I will adjust my code according to your recommendations (I still use d3 3.5.6, so seems like it's good time to migrate to d3 v4 😄 ).
