### ISSUE TITLE
Scale.ticks() sometimes returns ticks that don't span full domain

### ISSUE THREAD

**Issue by cssherry** [d3/d3-scale#86]
For example, when creating a scale:

`scale = d3.scaleLinear()
                  .domain([-2000000, 20000000000]);`

The returned `scale.ticks()` array is:
`[0, 2000000000, 4000000000, 6000000000, 8000000000, 10000000000, 12000000000, 14000000000, 16000000000, 18000000000, 20000000000]`

I originally thought changing the ticks functions (ln 154 - 161 in the d3.v4.js file I downloaded) to return `range(Math.floor(start/step) * step, Math.ceil(stop / step) * step + step / 2, step)` would fix the problem, but when I tried this, it didn't draw the axis properly

**Axis showing problem (the two lines' endpoints should be at 8B and -8K)**
<img width="383" alt="visual originally" src="https://cloud.githubusercontent.com/assets/6097953/20948460/170fd672-bbc9-11e6-94eb-72fbe422d1bb.png">

**Axis after bad fix**
<img width="413" alt="visual with bad fix" src="https://cloud.githubusercontent.com/assets/6097953/20948463/1c408d44-bbc9-11e6-8395-9e33391e39bb.png">

**Comment by mbostock** [comment]
It is the expected behavior that the first and last tick do not equal the minimum and maximum value in the domain. Ticks are “human-readable” rounded values (a power of ten multiplied by 1, 2 or 5), while the domain is arbitrary. For example:

```js
var x = d3.scaleLinear().domain([12, 59]);
x.ticks(5); // [20, 30, 40, 50]
```

If you want the ticks to exactly cover the domain, you must call [*scale*.nice](https://github.com/d3/d3-scale/blob/master/README.md#continuous_nice) after calling [*scale*.domain](https://github.com/d3/d3-scale/blob/master/README.md#continuous_domain). For example:

```js
var x = d3.scaleLinear().domain([12, 59]).nice(5);
x.domain(); // [10, 60]
x.ticks(5); // [10, 20, 30, 40, 50, 60]
```
