### ISSUE TITLE
paddingInner on band scale when domain has one item

### ISSUE THREAD

**Issue by asafbe** [d3/d3-scale#92]
I added paddingInner(0.02) to band scale, and looks like a padding exist when only one item in the domain. according to docs -  "The inner padding determines the ratio of the range that is reserved for blank space **between** bands". is this expected?

for example:
```
var x = d3.scaleBand()
        .paddingInner(0.02)
        .domain([0])
        .range([0,100]);

console.log(x.bandwidth()) // =>98
```

**Comment by mbostock** [comment]
It’s a degenerate case given that there’s only one band, so you have to imagine there’s a “virtual” band following the range, but the current behavior seems reasonable to me. If you special-cased *n* = 1 to remove any inner padding, then you’d experience a bigger discontinuity switching between *n* = 1 and *n* ≥ 2, which might be undesired.

**Comment by danielkeller** [comment]
I actually don't think the current behavior is reasonable. It would be more consistent to always have one less inner padding than domain element. Anyway, n=1 is already a special case, e.g. on [this line](https://github.com/d3/d3-scale/blob/v1.0.6/src/band.js#L23).

**Comment by mbostock** [comment]
I experimented with a solution for this in the [single-band branch](https://github.com/d3/d3-scale/tree/single-band); see 8c70d8bdda03561bbc674b147c3be8f21d7c429f.

The desire to treat point scales as a special case of band scales where paddingInner = 1 makes changing this behavior more difficult. The desired behavior of a point scale with a single element in the domain is to place the point in the middle of the range, and that doesn’t work if we ignore paddingInner when the number of elements is one (or zero). 

Hence the special case in the single-band branch: `n > 1 || paddingInner === 1`. But that in turn feels weird because it introduces a discontinuity in band scale behavior when paddingInner ≅ 1.

I can’t think of a good solution here, so I’m going to close this.

**Comment by gka** [comment]
Just stumbled on this as well, and I found it quite counter-intuitive that, regardless of the number of domain items, the _inner_ padding would ever affect the outer spacing.

https://github.com/user-attachments/assets/1d4bce98-d96f-443a-b03e-8329605e5b4a

Of course, as a user it's quite easy to catch this case, but first you have to notice it. Would be helpful to mention this in the documentation, at least.
